services:
  mongo-db:
    image: mongo:6.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo-user
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./databases/mongo:/data/db
    ports:
      - 27017:27017
    restart: always

  backend:
    container_name: backend
    build:
      context: ./backend
    expose:
      - "3000"
    depends_on:
      - mongo-db
    environment:
      MONGO_URL: mongodb://mongo-user:123456@mongo-db:27017/uleam-fcvt?authSource=admin
      PORT: 3000
      MONGO_DB_NAME: uleam-fcvt
      JWT_SEED: 57ed230b88787a77d8e4a13a11378174bbf12c88f354669c8208b3b24e2e2b2b
      JWT_EXPIRES_IN: 24h
    volumes:
      - ./backend/uploads:/app/uploads
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    expose:
      - "80"
    depends_on:
      - backend
    restart: always

  nginx:
    build: ./nginx
    expose:
      - "80"
    depends_on:
      - frontend
      - backend
      - nginx-proxy
      - letsencrypt
    environment:
      - VIRTUAL_HOST=uleam-fcvt.site,www.uleam-fcvt.site
      - LETSENCRYPT_HOST=uleam-fcvt.site,www.uleam-fcvt.site
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    restart: always

volumes:
  certs:
  html:
  vhostd:

networks:
  default:
    driver: bridge
